name: flutter_audio_games_template
description: "The __name__ game."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0-209.1.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.29.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_audio_games:
    path: ../flutter_audio_games/flutter_audio_games
  flutter_riverpod: ^2.4.9
  flutter_soloud: ^2.1.7
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  time: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - sounds/interface/
    - sounds/menus/
    - sounds/menus/voices/
    - sounds/music/
