name: flutter_audio_games_template
description: "The __name__ game."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-174.2.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.13.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.23.2
  flutter_riverpod: ^2.4.9
  flutter_soloud: ^2.0.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - sounds/interface/
    - sounds/menus/
    - sounds/menus/voices/
    - sounds/music/
